variable "instance_type" {
  type        = string
  description = "The type of instance to launch."
  default     = "t3.micro"
}

variable "name_prefix" {
  type        = string
  description = "The prefix to apply to the beginning of names generated by this module."
  default     = "dev"
}

variable "tags" {
  type        = map(string)
  description = "Key/Value pairs to pass to AWS as Tags."
  default     = {}
}

variable "instance_count" {
  type        = number
  description = "The number of instances to launch."
  default     = 1
  validation {
    condition     = can(parseint(tostring(var.instance_count), 10))
    error_message = "The instance count must be a number."
  }

  validation {
    condition     = var.instance_count > 0
    error_message = "The instance count must be greater than 0."
  }
}

variable "enable_systems_manager" {
  type        = bool
  description = "Enable Systems Manager for the instance."
  default     = false
}
